language: node_js
node_js:
  - node

branches:
  only:
  - develop

script:
  - yarn workspaces run build
  - yarn workspace @comment-faces/bot download-reddit-page
  - yarn workspace @comment-faces/bot extract-comment-faces

deploy:
  provider: script
  script: yarn deploy
